pipeline {
    agent any

    stages {
        stage('Uruchom playbook') {
            steps {
                ansiblePlaybook(
                    playbook: 'wypisz.yaml'
                )
            }
        }
    }
}
